### ISSUE TITLE
Question regarding performance with higher-end GPU cards

### ISSUE THREAD

**Issue by kaihuchen** [tensorflow/tfjs-core#111]
I tested the performance of deeplearnjs with a higher-end gaming laptop (Alienware 15 R3, with Nvidia 1070 8GB), and was surprised to see that it ran only 2-3 times faster than an older laptop with integrated graphics (Intel HD Graphics 3000).  Both tests were done under Chrome v59, using the CIFAR-10 example in the Model Builder example, set to the GPU mode).

So I compared both laptops again using an online WebGL test, http://www.fishgl.com/, and the result was similar, with the new laptop running at 2-3 times FPS than the old one.

I wonder if my observation above is the expected result?

**Comment by kaihuchen** [comment]
@nsthorat That's great to know! I am interested in using deeplearnjs for very-large-scale ensemble learning, and being able to get maximum amount of GPU juice through the browser is definitely going to help a lot.

**Comment by nsthorat** [comment]
Yes! We will be doing this soon. A lot of stuff is happening, so sorry this is taking longer than expected. I am excited about the project. Please reach out if you need anything with that experiment - and don't feel shy, send me an email to bug me!

**Comment by dsmilkov** [comment]
Closing since it's been a while. Feel free to re-open with a new discussion that's relevant to the latest state of the project.
