### ISSUE TITLE
How to use the demos?

### ISSUE THREAD

**Issue by SayHelloToWorld** [tensorflow/tfjs-core#112]
I opened the "/deeplearnjs/demos/adder/index.html"  in chrome browser, but the demo doesn't work at all. What's the right way to show the demo? Thanks a lot for answering my question.

**Comment by nsthorat** [comment]
Are you using `./scripts/watch-demo ./demos/adder/adder.ts` to build the demo?

**Comment by anguang1973** [comment]
in the command-line window, change the current directory to  deeplearnjs-master, then execute the command: node ./scripts/watch-demo ./demos/adder/adder.ts, then the watch-demo script compile the code and start a http server, open a browser, input the url  http://127.0.0.1:8080/demos/ in the address bar, you will see the demo.   Thanks nsthorat for the tip of scripts, I thought I should compile using tsc.

**Comment by CarmenPopoviciu** [comment]
I think this issue can be closed since both comments address the question very well and there don't seem to be any bugs the demo itself

**Comment by michaelvogt** [comment]
Just to share my experience on windows 10:
"./scripts/watch-demo ./demos/adder/adder.ts" opens the file watch-demo
"node ./scripts/watch-demo ./demos/adder/adder.ts" leads to an error that the file ~/demos/adder/adder.ts/adder.ts.ts could not be found.

"node ./scripts/watch-demo ./demos/adder/" works for me

**Comment by NitroBAY** [comment]
Okay thanks @michaelvogt I just couldn't figure out I had to put node before `./scripts/watch-demo demos/nn-art` so I was stuck for hours at the getting started step.
