### ISSUE TITLE
Provide a way to add custom GLSL functions in JS API.

### ISSUE THREAD

**Issue by znah** [tensorflow/tfjs-core#121]
One can also think of integration with [SaderGraph](https://github.com/unconed/shadergraph) to support users code to make queries to Tensors while abstracting away the data texture layout details. This way we can implement have [MathBox](https://github.com/unconed/mathbox)-like functionality that uses deeplearn.js under the hood.

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#75
