### ISSUE TITLE
mystifying problem with small canvas and requestAnimationFrame

### ISSUE THREAD

**Issue by silky** [tensorflow/tfjs-core#159]
in a project - https://github.com/silky/simple-cppn-deeplearn.js/tree/sizable - i've tried to make a resizable cppn interpolation example

if you clone it locally and open `interp.html` you'll see that it works fine.

on my computer, if you pick size 100x100, then click 'resize and generate', it just displays a single colour in the interpolated window. but if you try a 300x300, or anything larger than i think 120, it works normally.

this is beyond mystifying to me, as nowhere am i hardcoding anything about sizes.

it is very related to `requestAnimationFrame`, because if i simply do not animate, and just set it to arbitrary points in the interpolation, it works fine.

any leads would be super appreciated.

thanks! :)

**Comment by arthurjdam** [comment]
Interestingly, this doesn't happen when using `NDArrayMathCPU` instead of `NDArrayMathGPU`, though it stops animation. 

Your error happens right at 128 + 1 px width & height, but I can't seem to find any relevant hard-coded occurrences of 128 outside of unit tests.

**Comment by silky** [comment]
thanks for hte response @arthurjdam !

frustratingly, i still can't even use `NDArrayMathCPU` due to #116

**Comment by nsthorat** [comment]
128 x 128 is super suspicious. On macbooks, that's the maximum texture size (one dimension).

We were *supposed* to have fixed this (by physically storing square-ish memory, but logically what it was originally), but looks like we may have a bug. What would be really helpful is if you could just make a directory for each of these bugs so the demo renders, I can step through it directly from your github pages and tell you what's going on (so I don't have to figure out exactly what I need to clone & build, etc).

**Comment by hpssjellis** [comment]
@silky  Great example of a pure javascript cppn at  [ https://github.com/silky/simple-cppn-deeplearn.js/tree/sizable](https://github.com/silky/simple-cppn-deeplearn.js/tree/sizable) I updated the deeplearnjs to V0.3.8 and sent a PR since the demo was not working.

**Comment by nsthorat** [comment]
Closing this issue - if you still have an issue please file an issue in tfs: https://github.com/tensorflow/tfjs/issues
