### ISSUE TITLE
Demo: text generation

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs-core#237]
There are plenty of examples of generative text models on the web, for example:
http://karpathy.github.io/2015/05/21/rnn-effectiveness/

A fun demo idea would be to simply port a generative character RNN, or word RNN to the browser.

A slightly more involved demo would be to do the training in the browser. Given a chunk of text, learn to generate text like it. A nice UI could be built around this.

We would love somebody to build this - we would feature it on the homepage!

**Comment by hpssjellis** [comment]
Karpathys demo is at [https://github.com/karpathy/char-rnn](https://github.com/karpathy/char-rnn) and has been converted to Python and Tensorflow at [https://github.com/sherjilozair/char-rnn-tensorflow](https://github.com/sherjilozair/char-rnn-tensorflow) as @nsthorat has mentioned character RNN's are really fun to work with. My students used them to generate tweets and I have used them to make music and generate 3D printed shapes by feeding it object code (similar to g-code used by 3D printers). 

Bit over my head to convert the code but would really like to be involved if anyone wants to give it a try.

A github is here [https://github.com/hpssjellis/char-rnn-deeplearnjs](https://github.com/hpssjellis/char-rnn-deeplearnjs)

**Comment by hpssjellis** [comment]
Does anyone have a latest version of tensorflow  (V1.4) and a pre-trained character RNN model that they could convert to the format that deeplearnjs can upload using checkpointloader?  Or if you have the time could you run https://github.com/sherjilozair/char-rnn-tensorflow/blob/master/train.py with the tinyshakespeare dataset?

I stopped using Tensorflow and Magenta when most of my examples broke with each new version.

A pre-trained model ready to import into deeplearnjs would be a great starting point to make a character rnn.

**Comment by cvalenzuela** [comment]
@shiffman and I have been working on [this](https://github.com/ITPNYU/p5-deeplearn-js) project around deeplearn.js. It's still very much in its early stages but we built [this LSTM demo](https://itpnyu.github.io/p5-deeplearn-js/examples/es6/lstm/index.html) with https://github.com/sherjilozair/char-rnn-tensorflow using the tiny Shakespear dataset. Pairing this with @hpssjellis efforts to do the training on the browser will be amazing.

**Comment by hpssjellis** [comment]
@cvalenzuela and @shiffman that [demo](https://itpnyu.github.io/p5-deeplearn-js/examples/es6/lstm/index.html) is just amazing. You even have the temperature working. Thank you so much for sharing. Not sure if I can live up to the task of getting the training working. I still have a lot to learn about deeplearnjs

P.S. What version of Tensorflow did you use to generate the trained tinyShakespear models?

**Comment by nsthorat** [comment]
FWIW, I don't think we'll be able to train this in the browser yet - our Graph layer doesn't support recurrence. We're working on deeplearn.js eager mode which will enable recurrence with just a for loop. This will hopefully happen by end of year (it requires a bit of refactoring).

**Comment by hpssjellis** [comment]
Thanks @nsthorat that gives me a bit of time to learn more about deeplearnjs

**Comment by cvalenzuela** [comment]
I just wanted to share another demo I've been working on:
https://cvalenzuela.github.io/Selected_Stories/

I plan to add more models during the week.

**Comment by kolloldas** [comment]
I've made a name generator tool using deeplearn.js: https://namehacker.net but for some reason that I'm still investigating, it fails to load on Edge and generates junk on Safari. Works fine on Chrome though..

**Comment by dsmilkov** [comment]
I think between [Selected Stories](https://cvalenzuela.github.io/Selected_Stories/), and the [Translate demo](https://github.com/tensorflow/tfjs-examples/tree/master/translation) we just added to [tfjs-examples](https://github.com/tensorflow/tfjs-examples), we have a good starting point for a text-based model, so I'll be closing this thread.

Reopen if you have a specific idea for a text-based model that you'd like to contribute/see in our [examples repo](https://github.com/tensorflow/tfjs-examples).
