### ISSUE TITLE
Demo: place recognition on the webcam.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs-core#241]
The [MIT places database](http://places.csail.mit.edu/) is a rich dataset of places, with many models that train from this dataset to make a place prediction from an image.

It would be fun to port this model to a webpage, and we could have it classify locations from the webcam.

**Comment by ljvmiranda921** [comment]
This is interesting. I’d work on this first as a side-project then I’ll ping you for any updates!
