### ISSUE TITLE
Add functionality to invert a matrix.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs-core#244]
We can add this functionality as a util under a "linalg" file, like numpy does.

See: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.inv.html

**Comment by hpssjellis** [comment]
Solved my issue for a 2 x 2 matrix and extended my first deeplearnjs class :>
`
    class myNDArrayMathGPU extends deeplearn.NDArrayMathGPU {
       inverse2DSquare(b)  {       
          var myInverseMultiplier  = 1 / ( (b.getValues()[0] * b.getValues()[3]) - (b.getValues()[1] * b.getValues()[2]) )
          var myMatrixConverted = deeplearn.Array2D.new([2, 2], [b.getValues()[3]*myInverseMultiplier, b.getValues()[1]*-1*myInverseMultiplier, b.getValues()[2]*-1*myInverseMultiplier, b.getValues()[0]*myInverseMultiplier])
          return myMatrixConverted
      }
   }`


Demo at [https://hpssjellis.github.io/deeplearnjs-javascript-examples/a03-matrix-math.html](https://hpssjellis.github.io/deeplearnjs-javascript-examples/a03-matrix-math.html)


A demo of a pure javascript solution for any sized matrix [here](https://hpssjellis.github.io/deeplearnjs-javascript-examples/Unordered-javascript-examples/rocksetta/invert.html)

Converting that to typescript is out of my comfort zone.

**Comment by aptrishu** [comment]
where should this file be added?

**Comment by aptrishu** [comment]
I don't know, how do you propose to find an inverse by matrix multiplication. I am well versed with matrix maths. what I think is for 2*2 it can be easily calculated and for the rest we can use gauss jordan  method. Should be easy to implement.
