### ISSUE TITLE
Port NASNet Model

### ISSUE THREAD

**Issue by chaosmail** [tensorflow/tfjs-core#310]
NASNet Mobile_224 `[1]` achieves good classification accuracy (ImageNet 91.6% top-5 classification accuracy, vs. 80.3% in SqueezeNet v1.1) with a relatively small number of parameters (5.3M vs. 1.2M in Squeezenet v1.1). I think it would be cool to port this model from Tensorflow `[2]` over to Deeplearn.js.

`[1]`: https://research.googleblog.com/2017/11/automl-for-large-scale-image.html
`[2]`: https://github.com/tensorflow/models/tree/master/research/slim/nets/nasnet

**Comment by experiencor** [comment]
I am also interested in implementing NASNet (as well as MobileNet) in DeepLearn. The biggest challenge is the Depth-wise Separable Layer (https://towardsdatascience.com/types-of-convolutions-in-deep-learning-717013397f4d). It's not in the codebase of DeepLearn.

But I think that it's possible to make inference with NASNet using the API for matrix operating in GPU (https://deeplearnjs.org/#getting-started). @dsmilkov Do you think this method is as fast as it could be?

**Comment by nsthorat** [comment]
This would be great to port!

Have you started looking at what it would take? Is there anything other than depthwise separable convs?

Daniel is working on depthwise separable convs, we'll hopefully have it within a week so we can do MobileNet porting.

**Comment by experiencor** [comment]
It's a good new! Relu6 activation is also needed but it can be easily implemented by a chain of available operations. Waiting for the release of the depthwise separable conv. It's very useful for reducing the size of the weights.

**Comment by dsmilkov** [comment]
We just released a new version `0.3.11` with [depthwiseConv2d](https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/math.ts#L1641). Let us know if you run into any issues.

Cheers!

**Comment by experiencor** [comment]
@dsmilkov The code works great. I am able to implement MobileNet with depthwiseConv2d. Going to extend to realtime YOLO with MobileNet backend.

**Comment by nsthorat** [comment]
This is awesome! Can you send us a PR for MobileNet?

**Comment by experiencor** [comment]
I made the PR at https://github.com/PAIR-code/deeplearnjs/pull/361#issuecomment-345513954. This is my first time doing this. Please let me know if I need to conform to some rules.

**Comment by nsthorat** [comment]
NASNet still hasn't been implemented, let's reopen.
