### ISSUE TITLE
playground improvement: save to github authenticated account

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs-core#320]
We recently built a little demo that lets you play with deeplearn.js in a webpage:
https://deeplearnjs.org/demos/playground/index.html#400c3fc52db01860c1ddb8040bfcc4c9

The hash contains a public github gist that stores the js / html. We only have a run button because we will get rate limited by github gists. If we use the authenticated github API we can let people save gists to their account and share them.

Public save functionality is already implemented, just hidden for reasons above:
https://github.com/PAIR-code/deeplearnjs/blob/master/demos/playground/playground.ts#L84
https://github.com/PAIR-code/deeplearnjs/blob/master/demos/playground/index.html#L86

**Comment by ManrajGrover** [comment]
@nsthorat I believe this will involve creating a Github OAuth App and writing [a small backend](https://developer.github.com/v3/guides/basics-of-authentication/) for maintaining access token in session. Do we plan to host it on GCP?

**Comment by hpssjellis** [comment]
That [playground](https://deeplearnjs.org/demos/playground/index.html#400c3fc52db01860c1ddb8040bfcc4c9) is amazing. Really excited to see what people post.

A couple of questions:

Not really sure how to load a different gist? Would each gist have it's own url?


Can the console log be done without the use of  jQuery?

`  console.log(
      `${topClassesToProbs[className].toFixed(5)}: ${className}`);`

**Comment by nsthorat** [comment]
@ManrajGrover hmm unfortunately I think you're right. I need to think a little bit about whether we want to support that (right now we don't run an VM in GCP, it's actually just static files).

@hpssjellis 
- You can load another gist if you save a 'js' and an 'html' file part of the same gist. Then you can use the gist ID in the URL after our hash.
- That's actually not jquery, that's actually a "template literal placeholder": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by hpssjellis** [comment]
@nsthorat 

Thanks for the lesson on "template literal placeholders" seems javascript is changing a lot lately.

Still a bit lost on using my own gist with the playground.

Your example at 

[https://deeplearnjs.org/demos/playground/index.html#400c3fc52db01860c1ddb8040bfcc4c9](https://deeplearnjs.org/demos/playground/index.html#400c3fc52db01860c1ddb8040bfcc4c9)

Has a hash on the end of the URL that looks like a public gist, but I can't find it.

My test gist at 

[https://gist.github.com/hpssjellis/7de218f7616a3b7fb1f85c71b3a9ee66](https://gist.github.com/hpssjellis/7de218f7616a3b7fb1f85c71b3a9ee66)

Has a hash on the end but I can't load it into the playground. Just replacing the other hash does not seem to work.

**Comment by nsthorat** [comment]
Check out https://gist.github.com/anonymous/400c3fc52db01860c1ddb8040bfcc4c9

Ah yeah, we're only reading public gists right now. When we get cycles we'll fix this.

**Comment by hpssjellis** [comment]
@nsthorat 

That works. Looks like I can fork it and then use the forked hash

[https://deeplearnjs.org/demos/playground/index.html#05af4e9e3e11f6e38b40b412926fa7cc](https://deeplearnjs.org/demos/playground/index.html#05af4e9e3e11f6e38b40b412926fa7cc)

**Comment by dsmilkov** [comment]
Closing this since we are going to use [Observable Notebooks](https://beta.observablehq.com/) for notebook-like examples/tutorials.
