### ISSUE TITLE
Demo: Autoencoder?

### ISSUE THREAD

**Issue by ajinkyai** [tensorflow/tfjs-core#348]
Hi,
Would it be a good idea to add a demo on a simple Autoencoder?

I can work on a simple example on denoising MNIST.

**Comment by dsmilkov** [comment]
Autoencoder is a great idea. If you go with MNIST, I like the approach in [this Keras blog](https://blog.keras.io/building-autoencoders-in-keras.html), but we're open to any ideas.

**Comment by kimamula** [comment]
Is it possible to implement convolutional autoencoder without `conv2dTranspose` method in `Graph` class?

**Comment by nsthorat** [comment]
This would be a cool demo! Maybe we can move demo ideas to our community discussion, meanwhile I will close this bug: https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs
