### ISSUE TITLE
Various NaN and ~0 precision bugs in GPU-mode on Win64, and Thinkpad X1 Carbon V3 (debian-based)

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs-core#357]
Still researching - but I think WebGL on various hardware devices might not report 0 as true zero:

https://stackoverflow.com/questions/11810158/how-to-deal-with-nan-or-inf-in-opengl-es-2-0-shaders

![capture](https://user-images.githubusercontent.com/306276/32874792-43b454fc-ca49-11e7-9e1f-2f58d380c439.PNG)

**Comment by nkreeger** [comment]
[win64-log.txt](https://github.com/PAIR-code/deeplearnjs/files/1507090/win64-log.txt)

**Comment by dsmilkov** [comment]
Hey @nkreeger is this still relevant?

**Comment by nkreeger** [comment]
Should be resolved.
