### ISSUE TITLE
Issue with PyTorch dumper script

### ISSUE THREAD

**Issue by mishra-avinash** [tensorflow/tfjs-core#379]
PyTorch follow different convention than tensorflow for input image for example 
PyTorch input image shape: [inDepth, height, width] 
PyTorch filter shape [outDepth, inDepth, filterHeight, filterWidth].
TF input image shape:  [height, width,inDepth]. 
TF filter shape [filterHeight, filterWidth, inDepth, outDepth].
The Conv2d function of deeplearnjs also expect input image and filter in TF format but in the PyTorch dump script we are not transposing weights to suit Conv2d function. We should also change the shape in manifest file accordingly. But i can not find any line of code that does it. Could you please check this out.
Let me know, if i misunderstood something or issue is not clear.

**Comment by nsthorat** [comment]
I think the transposing should probably happen in user code (for now) - you can use `math.transpose()`. We may get to a point where we also dump the format of the weights so that we can automatically do transposing, but that will likely happen when we do more end-to-end model conversion.
