### ISSUE TITLE
Different pixel value while using FromPixel function 

### ISSUE THREAD

**Issue by mishra-avinash** [tensorflow/tfjs-core#380]
I have trained a image classification **model in Pytorch and ported that model to deepleanjs** . When i am trying to use this in deeplearnjs i am getting  different (wrong) results, for few images, as compare to pytorch model in python.
I dig in to find the reason behind that and i found that the pixel value that i am feeding in to the inference model in deeplearnjs is somewhat different than pixel value that i feed to PyTorch model in python.
Below are the code snippet showing both values. Input image size is (224x224x3)

**In python** 
`img = Image.open( img_path ).convert("RGB")`
`img_array = np.asarray( img, dtype="float32" )`
`img_array.flatten()[0:20]`
**output:** [ 124.,  119.,  113.,  146.,  143.,  138.,  179.,  178.,  173.,
                 191.,  188.,  181.,  194.,  188.,  176.,  217.,  207.,  195., 221.,  209.], dtype=float32)

**In deeplearnJs**
`const input_image = Array3D.fromPixels(InputImgElement)`
`console.log("image  pixel values",input_image.getValues())`
 `console.log("image size",input_image.shape)`
**output:** Float32Array(150528)
                  [124, 120, 109, 147, 143, 132, 181, 178, 169, 191, 189, 177, 192, 188, 177, 213, 209, 198, 
                 217, 210, 202, 224, 219, 213, 229, 225, 216, 231, 228, 221, 232,.........]
                 image size : [224, 224, 3]

Do you have any clue why this values are different? is there any that while using webGL texture to load pixel values can change values by small value?

**Comment by mishra-avinash** [comment]
[https://imgur.com/a/lwvPG](url)
link for image that i am loading.

**Comment by nsthorat** [comment]
Ah this is no good, there may be some difference in PIL vs the way browsers decode! Can I ask what browser are you using?

Can you also print one more thing - using the ImageData API in JavaScript print out the values you get? This will tell us if there's a difference in image decoding from the browser vs PIL, or if it's something in the way we upload the values to the GPU.

Here is how you would do it:
https://stackoverflow.com/questions/10754661/javascript-getting-imagedata-without-canvas

**Comment by mishra-avinash** [comment]
I am using Chrome (Version 62.0.3202.62 (Official Build) (64-bit)) 
here is the output from ImageData API
[124, 120, 109, 255, 147, 143, 132, 255, 181, 178, 169, 255, 191, 189, 177, 255, 192, 188, 177, 255, 213, 209, 198, 255, 217, 210, 202, 255, 224, 219, 213, 255, 229, 225,...]
it has the same value as output from deeplearnjs but in format 'RBGA'
