### ISSUE TITLE
devtoolsFormatters object formatter extension?

### ISSUE THREAD

**Issue by tmcw** [tensorflow/tfjs-core#382]
Has anyone considered writing (or has anyone already written) a [custom object formatter](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview) for Chrome devtools in combination with deeplearn.js? This would make it possible to view Array2D data structures visually as the matrices that they represent mathematically.

**Comment by nsthorat** [comment]
This is a really cool idea, I haven't heard of anyone working on this.

This would be a phenomenal contribution if anyone's up for it.

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#93
