### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by ivikash** [tensorflow/tfjs-core#393]
Hello Team, I see a poll on Twitter for the new API. https://twitter.com/deeplearnjs/status/935335651607826432

I am just opening an issue here to have follow-up discussions. Also, please let me know ways in which I can contribute to this. 

As @michalwols pointed a beautiful piece of code at https://twitter.com/michalwols/status/935344624457211904

```javascript
const stack = (...layers) => x => {
  let output = x
  for (const layer of layers) {
    if (layer) output = layer(output)
  } 
  return output
}

const convLayer = stack(
  Conv(10, 3), 
  batchNorm, 
  relu
)
```

I also firmly believe a similar API would be great to have. We can have functional paradigms and data-last API

**Comment by nsthorat** [comment]
I agree. We will provide something like this once the lower-level layers have matured (expect this type of API within a couple months).

**Comment by nsthorat** [comment]
We now have a higher-level Keras-compatible layers API as part of TensorFlow.js! https://github.com/tensorflow/tfjs
