### ISSUE TITLE
Verbally Teachable Machine

### ISSUE THREAD

**Issue by hma02** [tensorflow/tfjs-core#397]
It would be cool to have a verbally teachable machine besides the existing [visually teachable machine](https://teachablemachine.withgoogle.com/).

some ideas:
- Let user type in a text label, say "apple", or let them select an apple Image as label. Then let them pronounce "apple" as many times. Then do the same for another label, say "banana", and so on.
- As easy and intuitive as possible, doesn't need to be as performant as state of art speech recognition model.

Not sure if I will have time to work on this. Just starting this thread as I came up with the idea

**Comment by nsthorat** [comment]
Would love to see this - maybe this discussion could be moved to our community mailing list: https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs
