### ISSUE TITLE
how to train an lstm

### ISSUE THREAD

**Issue by husseinabed** [tensorflow/tfjs-core#414]
Hey,
Im traing to build a model to give me a short sentence based on a facebook comments

1. I'm not sure what is the labels if there is a labels to train with
2. how to train a lstm 

can anybody explain to me that demo 
https://github.com/PAIR-code/deeplearnjs/blob/master/demos/lstm/lstm.ts
thanks

'

**Comment by nsthorat** [comment]
Now we can train LSTMs with the new layers API: https://github.com/tensorflow/tfjs
