### ISSUE TITLE
i have a question about demo

### ISSUE THREAD

**Issue by W285887933** [tensorflow/tfjs-core#424]
Uncaught Error: Module parse failed: Unexpected token (79:12)
You may need an appropriate loader to handle this file type.
| const optimizer = new SGDOptimizer(learningRate);
| 
| const inputs: Array1D[] = [
|     Array1D.new([1.0, 2.0, 3.0]),
|     Array1D.new([10.0, 20.0, 30.0]),
    at Object.<anonymous> (bundle.js:70)
    at __webpack_require__ (bundle.js:20)
    at bundle.js:63
    at bundle.js:66

what's up?  what file i need install?

**Comment by ManrajGrover** [comment]
@W285887933 Hi there! Did you transpile the typescript file while building the code? If yes, please share the steps to reproduce this error. Also, please share the following:

1. DeeplearnJS version
2. Node version
3. Webpack version and config

**Comment by hpssjellis** [comment]
Which demo are you loading @W285887933  ?

**Comment by ManrajGrover** [comment]
@W285887933 Yes, you can use webpack + ES6. But the code you are trying to bundle is written in TypeScript. Hence, you would need to transpile the TypeScript code to ES6. Here's a [guide](https://webpack.js.org/guides/typescript/) on how to do that.
