### ISSUE TITLE
Can't change image on the /models/squeezenet/squeezenet.ts

### ISSUE THREAD

**Issue by QuantumInformation** [tensorflow/tfjs-core#469]
The example has the cat as the picture

https://github.com/PAIR-code/deeplearnjs/blob/master/models/squeezenet/cat.jpg

But when I try change this to another image I get

`deeplearn.js:12653 Uncaught (in promise) Error: The output # of rows (35.5) must be an integer. Change the stride and/or zero pad parameters`

**Comment by MariasStory** [comment]
Same for me.
Has something to do with convolution operations steps and dimensions. 

Can someone, please, look into it?

We need to use any image.

**Comment by chaosmail** [comment]
There is no preprocessing (scaling) implemented in the demo and hence your picture needs too have the exact dimensions as the cat.jpg (width, height and depth/RGB).

**Comment by nsthorat** [comment]
Yeah, we don't resize in the model. We're taking contributions though! You can use `math.bilinearResize3D`.

**Comment by MariasStory** [comment]
Hi, this is what I was expecting. I guess that the model is trained on the image dimensions 227x227.
@nsthorat are you sure that you did not misspell the math.bilinearResize3D. I can't find it. Can you please give some example?

**Comment by ManrajGrover** [comment]
Hi @MariasStory, the function is defined [here](https://github.com/PAIR-code/deeplearnjs/blob/462beaf/src/math/math.ts#L1938). You can read more about it in the [documentation](https://deeplearnjs.org/docs/api/classes/ndarraymath.html#resizebilinear3d).

**Comment by MariasStory** [comment]
Cool. Thanks worked for me:
const pixels = math.resizeBilinear3D(dl.Array3D.fromPixels(cat),[227, 227]);

**Comment by nsthorat** [comment]
Thanks for correcting me @ManrajGrover :)

Adding resizeBilinear3D with [227, 227] if the dimensions of the input aren't [227, 227] to the model itself would be great if somebody wants to send me a PR!

**Comment by MariasStory** [comment]
There is a problem with this approach:
Nonstandard image dimensions are deformed and cannot be recognized.

A somewhat better approach is to cut the square aria out of the image and then resize.

**Comment by nsthorat** [comment]
Closing this out since we've updated the demo.
