### ISSUE TITLE
I wouldn't recommend using Visual Studio Code for development

### ISSUE THREAD

**Issue by QuantumInformation** [tensorflow/tfjs-core#481]
It's quite unusual to offer guidance on what IDE to use, I would remove this for sure.

**Comment by nsthorat** [comment]
You can always ignore it :)

We suggest it because we were getting contributions with lots of style problems. The IDE suggestion enforces auto-save formatting, vastly minimizing review time.

**Comment by QuantumInformation** [comment]
You can enforce at the git commit level with https://www.npmjs.com/package/pre-commit

**Comment by QuantumInformation** [comment]
Also force lint tests to pass with travis IIRC

**Comment by MariasStory** [comment]
Hi @QuantumInformation, you have some interesting suggestions, but I do support the idea of the project related development stile recommendations. The exact implementation can be discussed and maybe some options proposed. Still, some user guides help all to get in sync. 
If you are to continue this discussion, it would be nice to propose another/similar best practice development procedures.

**Comment by QuantumInformation** [comment]
Here is an IDE independent way to build deeplearn projects:

https://github.com/QuantumInformation/deeplearnjs-playground
