### ISSUE TITLE
Can this work on nodejs?

### ISSUE THREAD

**Issue by plantain-00** [tensorflow/tfjs-core#49]

**Comment by dsmilkov** [comment]
It should, but it's blocking on #19 being fixed first.

**More detail**
You can use https://github.com/stackgl/headless-gl which implements the WebGLContext in node.js. The change you need to make is here: https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/webgl/webgl_util.ts#L89 

The bigger problem is that headless-gl doesn't support `OES_texture_float` extension which our library currently depends on. The good news is that we are working to get around that limitation since we wants to support large number of mobile devices (including iOS).

**Comment by RubenSandwich** [comment]
@dsmilkov The link: https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/webgl/webgl_util.ts#L89, is now a 404. Could you please update it?

**Comment by dsmilkov** [comment]
Updated!

**Comment by dfoody** [comment]
I've updated my branch of headless-gl (https://github.com/dfoody/headless-gl) to include support for `OES_texture_float` as well as `WEBGL_get_buffer_sub_data_async`. It's only been tested on OSX and only with basic deeplearn.js examples (e.g. matrix multiplication).

You can give it a try as follows:
```
npm install deeplearn-gl
npm install deeplearn
```
(FYI, the install and build can take a while - ~15m).

The most important point about using it is to require `deeplearn-gl` before `deeplearn`.
Here's an example:
```
var gl = require('deeplearn-gl')
var dl = require('deeplearn');
var math = new dl.NDArrayMath('webgl');
var size = 3000;

var start = Date.now();

var a = dl.Array2D.ones([size, size]);
var b = dl.Array2D.ones([size, size]);

var result = math.matMul(a, b);

var promise = result.data().then(function(data) {
  console.log("done in ", (Date.now()-start)/1000, "seconds with value", data[0]);
}).catch(console.log);
```

**Comment by erikwilson** [comment]
Thanks for working on this @dfoody ! I am having some problems building deeplearn-gl on OSX, it seems to require cairo which I can brew install but the next step errors on gclient, gn, and ninja commands, which are a bit more difficult to find & install.

**Comment by dfoody** [comment]
@erikwilson looks like I have a bit of a packaging problem.
I'll get it fixed, but until then try the following:

`npm install deeplearn-gl --force` (or just clone the repository https://github.com/dfoody/headless-gl) then go into the directory (`node_modules/deeplearn-gl`) and run `npm install` from there. This will download all the tools needed (gclient, etc.) to build it.

Let me know if you have any other issues!

**Comment by nsthorat** [comment]
Wow, this is wonderful work! If you go post it on the TensorFlow github issue (the second most commented on issue) I'm sure people would love your work:

https://github.com/tensorflow/tensorflow/issues/37

I look forward to playing around with this! Have you had a chance to see whether performance is the same as on the web? I assume it's comparable, but just curious.

**Comment by dfoody** [comment]
@nsthorat thanks - I posted there as well.
In terms of performance I tested a matmul of two 6000x6000 matrices (see code below)
On chrome it averaged around 12.5s. In node.js it averaged about 14.5s.

On the  node side, I suspect the performance difference may be the time to read the data from the pixel buffer (I map the buffer and the memcpy into the node typed array - there might be a way to directly copy the data into the node typed array which might improve performance - but angle does not expose glGetBufferSubData API publicly for some reason).

@erikwilson the install process should now be fixed. You should be able to do:
```
brew install pkg-config cairo pango libpng jpeg giflib
npm install deeplearn-gl
```

Here's the matmul code I used:
```
var math = new dl.NDArrayMath('webgl');
var size = 6000;

var start = Date.now();

var a = dl.Array2D.ones([size, size]);
var b = dl.Array2D.ones([size, size]);

var result = math.matMul(a, b);

var promise = result.data().then(function(data) {
  console.log("done in ", (Date.now()-start)/1000, "seconds with value", data[0]);
}).catch(console.log);
```

**Comment by erikwilson** [comment]
Thanks! It seems to mostly work but I am getting some weird results with mocha tests. It would be nice if we could create a math object directly from the result of gl/headless-gl/deeplearn-gl, something like:

```javascript
const dl = require('deeplearn')
const gl = require('deeplearn-gl')
const context = new dl.GPGPUContext(gl())
const backend = new dl.MathBackendWebGL(context)
const math = new dl.NDArrayMath(backend)
```

^ That doesn't seem to work though, not sure if it should or what I am doing wrong.

I'm also curious if it might be helpful to remove the dependency of document and canvas out of webgl_util.ts or at least provide the options for a generator like headless-gl's createContext(width, height, options)
via https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/backends/webgl/webgl_util.ts#L37

**Comment by nsthorat** [comment]
Try making a new math like this (and using ENV.setMath)

https://github.com/PAIR-code/deeplearnjs/blob/master/demos/nn-art/cppn.ts#L79

**Comment by erikwilson** [comment]
Perfect, thank you @nsthorat ! 

The error gave a clue with `Use dl.ENV.math instead of constructing your own NDArrayMath.`

The following works perfectly: 
```javascript  
  const dl = require('deeplearn')
  const gl = require('deeplearn-gl')
  const context = new dl.GPGPUContext(gl())
  const backend = new dl.MathBackendWebGL(context)
  const math = new dl.NDArrayMath(backend)
  dl.ENV.setMath(math)
```

I can also use `const gl = require('gl')` but also get the following warning with initially correct results:
```
objc[77798]: Class SwapLayer is implemented in both ./node_modules/deeplearn-gl/build/Release/webgl.node (0x106797670) and./node_modules/gl/build/Release/webgl.node (0x109c7cc50). One of the two will be used. Which one is undefined.
```

**Comment by erikwilson** [comment]
Actually using the ``require('gl')`` only worked because my tests had a previous ``require('deeplearn-gl')`` which stubs out document and canvas.

**Comment by erikwilson** [comment]
@nsthorat full stack trace of when I try to just use ``const gl = require('gl')`` in the above example:

```
./node_modules/deeplearn/dist/math/backends/webgl/webgl_util.js:7
    var canvas = document.createElement('canvas');
                 ^

ReferenceError: document is not defined
    at Object.createWebGLRenderingContext (./node_modules/deeplearn/dist/math/backends/webgl/webgl_util.js:7:18)
    at Object.createWebGLContext (./node_modules/deeplearn/dist/math/backends/webgl/gpgpu_util.js:60:25)
    at new GPGPUContext (./node_modules/deeplearn/dist/math/backends/webgl/gpgpu_context.js:53:34)
    at Object.<anonymous> (./gpu-test/backend-test.js:4:17)
```

on deeplearn v0.4.0

Do we actually need to create a new gl context and if so would it be better to pass a function into a new GPGPUContext?

**Comment by nsthorat** [comment]
Hmm.. That method shouldn't be called because you are passing a gl() directly. 

That bypasses this, which is where document.createElement is transitively called.
https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/backends/webgl/gpgpu_context.ts#L43

Can you make sure the output of gl() is not null?

**Comment by erikwilson** [comment]
@nsthorat sorry you are right gl() without params returns null but event with a proper gl context I still get the following:

```
./node_modules/deeplearn/dist/environment.js:24
    var tempCanvas = document.createElement('canvas');
                     ^

ReferenceError: document is not defined
    at getWebGLRenderingContext (./node_modules/deeplearn/dist/environment.js:24:22)
    at isWebGLVersionEnabled (./node_modules/deeplearn/dist/environment.js:41:14)
    at Environment.evaluateFeature (./node_modules/deeplearn/dist/environment.js:137:17)
    at Environment.get (./node_modules/deeplearn/dist/environment.js:111:39)
    at new GPGPUContext (./node_modules/deeplearn/dist/math/backends/webgl/gpgpu_context.js:55:31)
```

**Comment by nsthorat** [comment]
Ahh, crap. For now, do the following before you do anything else. Once we make this more official we can add a fix to the core library.

```
const features = {
  'WEBGL_VERSION': 2,
  'WEBGL_FLOAT_TEXTURE_ENABLED': true,
  'WEBGL_GET_BUFFER_SUB_DATA_ASYNC_EXTENSION_ENABLED': true;
};
ENV.setFeatures(features);
```

**Comment by nsthorat** [comment]
Basically those flags will get evaluated by the library, and thus call the underlying `document.createElement` call which you need to avoid. This will set them explicitly and will avoid having to call `document.createElement`.

Eventually, we can test whether we're in a node.js context with deeplearn-gl here: https://github.com/PAIR-code/deeplearnjs/blob/master/src/environment.ts#L63

**Comment by dfoody** [comment]
deeplearn-gl creates a global document object (with createElement on it that supports a regular canvas object and gl) so deeplearn works directly with it with no special changes or code - you just need to require deeplearn-gl first.
But, obviously, putting objects in the global context isn't a great long term solution. Would be better to have a central hook that could be used to pass in the context objects.

**Comment by erikwilson** [comment]
That worked, thanks @nsthorat !

It looks like a significant amount of work went into enabling those three extensions @dfoody , are you planning to PR stackgl/headless-gl so they end up in the main branch?

**Comment by dsmilkov** [comment]
With deeplearn.js becoming TensorFlow.js, we are super excited to share that [we are actively working](https://js.tensorflow.org/faq/) on node.js bindings that will use the TensorFlow C API. Stay tuned!

**Comment by nsthorat** [comment]
This is the tracking bug for nodejs: https://github.com/tensorflow/tfjs/issues/36
