### ISSUE TITLE
Add store and recall functionality to knn-image-classifier

### ISSUE THREAD

**Issue by HalfdanJ** [tensorflow/tfjs-core#490]
Would be useful to have a functionality that can save and recall the state of the knn image classifier. 

Storing could be something like this: 

```js
const storedData = knn.store();

// Resulting in something like this:
storedData = { 
   classLogitsMatrices: [ ... ]
   classExampleCount: [ ... ] 
}
``` 

This object can then either be stored as a json file, or stored to something like localStorage. 

To recall it could either be in the `knn.load(storedData)` function as a parameter or a new `knn.recall(storedData)` function call.

If you agree with this syntax, then I can make a PR for it.

**Comment by nsthorat** [comment]
That seems reasonable to me, have you had a look at how big that file will be for a typical session? JSON is a horrible serialization format for weights, but unfortunately if we want to just download the weights as a float32 byte stream we'll need 2 files (weights, and manifest).
