### ISSUE TITLE
Calling JSON.stringify() on NDArray leads to circular object value error

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs-core#498]
To reproduce:

```javascript
const x = deeplearn.Array1D.new([1]);
console.log(JSON.stringify(x));
```

See the error:  `TypeError: cyclic object value in ...`

Seen at deeplearn.js version 0.3.17.

**Comment by caisq** [comment]
FYI @dsmilkov @nsthorat @michael-terry

**Comment by nsthorat** [comment]
We now support `.print()` and `.toString()` on `Tensor`s.
