### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by lunzhang** [tensorflow/tfjs-core#503]
Hi I'm getting errors on my ide Atom and VSCode for typescript generic type.

For example, in demos/cppn.ts file, Array2D declarations are getting this error 

> Generic type 'Array2D<T, keyof, DataTypes>' requires 3 type argument(s).

**Comment by dsmilkov** [comment]
I'm using VSCode and I don't get that error at HEAD (are you merged at HEAD)? Also which version of deeplearn do you want installed with your demos?

You can see it in `demos/node_modules/deeplearn/dist/version.js`.

Thanks

**Comment by lunzhang** [comment]
I got off work so I can't check the version but my branch is up to date.  The errors also lie outside of demos.

I think the error happens because Array2D is a generic typed class.

`export class Array2D<D extends DataType = DataType> extends NDArray<D, '2'>` [link](https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/ndarray.ts#L546)

so when declaring Array2D it should be done like Array2D<DataType>.

**Comment by lunzhang** [comment]
I'm currently on version '0.3.16'

**Comment by lunzhang** [comment]
I found out that the problem was because my typescript version was outdated.

**Comment by dsmilkov** [comment]
Dependencies have changed. Try removing node_modules:
 - cd to the base of the repo.
 - `rm -r /node_modules`
 - `rm -r /demos/node_modules`
 - `yarn prep`

This will reinstall all dependencies and update the typings

**Comment by lunzhang** [comment]
Hi, I tried reinstalling the dependencies, still getting ts error.
