### ISSUE TITLE
Unpooling2D operation

### ISSUE THREAD

**Issue by kozko2001** [tensorflow/tfjs-core#507]
I was thinking of making a version of the [Universal Style Transfer via Feature Transforms](https://arxiv.org/pdf/1705.08086.pdf) for deeplearningjs. And seems that is feasible (I have to test yet if possible to load all 130M of VGG19).

For implementing the autoencoder I don't see any operation on the documentation for doing unpooling. I have miss something? or is just that it has to be implemented?

Thanks!

**Comment by dsmilkov** [comment]
I might be wrong, but seems to me that unpooling is basically the backprop of pooling, and we already expose that. See [`math.maxPoolBackprop`](http://deeplearnjs.org/docs/api/classes/ndarraymath.html#maxpoolbackprop). Hope this helps!
