### ISSUE TITLE
NDArray.make creates array but then dataSync() returns null

### ISSUE THREAD

**Issue by kristian-io** [tensorflow/tfjs-core#524]
I am trying simply to create a new NDArray directly using NDArray.make or  new NDArray() and then retrieve the values using dataSync() but I am getting null ( before version 0.4.1 I was getting undefined)

>const dl = require('deeplearn');
>  var q = dl.Array3D.new([3,1,1], [1, 2, 3]);
> q.dataSync()
Float32Array [ 1, 2, 3 ]       // works as expected
> var q = dl.NDArray.make([1,1,1], [4,5,6])
> q.dataSync()
null        
> var q = new dl.NDArray([1,1,1], [4,5,6])                           
> q.dataSync()
null                               

I expect this to be some sort of banality from my side but from the documentation, I dont see what I am doing wrong.

NDArray.make
> Makes a new ndarray with the provided shape and values. Values should be in a flat array.

Thanks!

**Comment by kristian-io** [comment]
If I do this:

>r = new dl.NDArray.randUniform([3,3,3], 0,1)
> q = dl.NDArray.like('float32', r)

I am getting:

TypeError: another.**dataSync** is not a function
    at Function.NDArray.like (C:\...\deeplearn\dist\math\ndarray.js:102:48)
    at repl:1:20
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)

Which points to the same issue with dataSync()

**Comment by kristian-io** [comment]
Ok, I have found the way how to construct NDArray in a way that dataSync works (sorry for dumping here the whole thought process :) )

>i = dl.NDArray.make([3,1,1], { values: [3,4,5] });
> i.dataSync()
[ 3, 4, 5 ]

**Comment by nsthorat** [comment]
NDArray is gone, and make is also not the public API for making tensors now.
