### ISSUE TITLE
Deploying fast-style-transfer-deeplearnjs

### ISSUE THREAD

**Issue by Yagun** [tensorflow/tfjs-core#528]
Hi,

I tried to build "Fast Style Transfer Deeplearnjs" sample to deploy and run it on my local node.js server. After executing the deploy-demo script I got a single HTML file (730 kB) in a new folder (I called it "distr"). I tried to run it, but it does not work properly. It shows the controls, but does not show the pictures (source and style) and the button does nothing.

Please explain how to build the sample properly and what files and folders does it need to work. For example, it requires a script from bower_components\webcomponentsjs folder, I copied this folder to the distr folder, but it changed nothing.

I asked the sample developer (reiinakano) about this and he answered: "I've never actually used the deploy-demo script before so I'm not sure how that works."

Please explain me how to deploy this sample.

Thank you in advance.

**Comment by ManrajGrover** [comment]
@Yagun If you wish to view the demo, you should use `watch-demo` script. It will start its own nodejs server and you will be able to view the demo on `http://127.0.0.1:8080/demos/fast-style-transfer/`. The shell command would be `./scripts/watch-demo demos/fast-style-transfer`.

**Comment by Yagun** [comment]
@ManrajGrover  thank you for your answer, but it is not what I need. The "watch-demo" script runs the demo with "watchify" showing additional console window and watching for script changes, so you can change the scripts and see what happens. It is a debug mode. And it is not what I want. There are "deploy-demo" and "build-standalone" scripts, but no explanation how to get a standalone **working** version of a particular example which is not running that debug console window and does not watch for script changes.

What I need is:
1. Run a script (deploy-demo, build-demo, build-standalone or whatever).
2. Get a folder with the built sample project files. (Including deeplearnJS library as a .js file).
3. Copy (or upload) those files to some web server (local or web hosting).
4. Open an URL and see a working sample.

As I understand, either "deploy" or "build-standalone" should work this way.

**Comment by Yagun** [comment]
Related issue:
https://github.com/PAIR-code/deeplearnjs/issues/543

**Comment by ManrajGrover** [comment]
@Yagun `build-standalone` script is for building the library and it's minified version. `deploy` script is used by `make-website` script for building the demo for the website. I don't think we have a script that brings everything together for a particular demo for standalone usage. We welcome PRs for the same.
