### ISSUE TITLE
Squeezenet sample data

### ISSUE THREAD

**Issue by Yagun** [tensorflow/tfjs-core#529]
I looked at the Squeezenet sample and found that it loads a model from https://storage.googleapis.com/learnjs-data/checkpoint_zoo/squeezenet1_1 

As I understand, the network config is in a manifest.json file on that website. Right?

What file(s) contain the weights of the pre-trained Zoo network?

Is there a list of all the pre-trained networks? https://storage.googleapis.com/learnjs-data/ shows "Access Denied" error.

Thanks.

**Comment by nsthorat** [comment]
We're now TensorFlow.js. We have a MobileNet example here: https://github.com/tensorflow/tfjs-examples/tree/master/mobilenet
