### ISSUE TITLE
Expose API to dispose variables

### ISSUE THREAD

**Issue by arvind** [tensorflow/tfjs-core#540]
In eager mode, a `dl.ENV.math.disposeVariables` function would be useful to allow us to recreate models with the same-named variables without incurring a memory leak. For now, I'm using the following:

```js
    for (const varName in math.registeredVariables) {
      const v = math.registeredVariables[varName];
      v.dispose();
      delete math.registeredVariables[varName]; // setting to null is more performant, but dl enumerates the keys of registeredVars.
    }
```

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#107
