### ISSUE TITLE
Error in net.ts

### ISSUE THREAD

**Issue by Yagun** [tensorflow/tfjs-core#543]
When building fast-style-transfer-deeplearnjs (with ./scripts/deploy-demo ... ), error text  :

TypeScript error: src/net.ts(7,14): Error TS2420: Class 'TransformNet' incorrectly implements interface 'Model'.
Types of property 'predict' are incompatible.
Type '(preprocessedInput: Array3D<"float32" | "int32" | "bool">) => Promise<Array3D<"float32" | "int32"...' is not assignable to type '(input: NDArray<"float32" | "int32" | "bool", "0" | "1" | "2" | "3" | "4" | "higher">) => NDArray...'.
Type 'Promise<Array3D<"float32" | "int32" | "bool">>' is not assignable to type 'NDArray<"float32" | "int32" | "bool", "0" | "1" | "2" | "3" | "4" | "higher">'.
Property 'id' is missing in type 'Promise<Array3D<"float32" | "int32" | "bool">>'.

**Comment by dsmilkov** [comment]
`deploy-demo` is meant to be called by `make-website`, which we only call when we are regenerating our website.

Can you share with us your use case?

If you are developing the model use
```
./script/watch-demo demos/fast-style-transfer/
```
as described in our [Development section](https://github.com/PAIR-code/deeplearnjs#development).

If you are trying to build a production version instead, run
```
./scripts/build-demo demos/fast-style-transfer/
```
This will generate and store the bundle js in `demos/fast-style-transfer/bundle.js`

**Comment by dsmilkov** [comment]
Also make sure you are synched with master and re-run `yarn prep` so that your `node_modules` are up to date
