### ISSUE TITLE
MobileNet version

### ISSUE THREAD

**Issue by Yagun** [tensorflow/tfjs-core#552]
There are different Mobile Nets in that Google science paper. For example:
0.75 MobileNet-224
1.0 MobileNet-192
MobileNet-160

Also there are 1.0 and 1.1 versions of the nets.

Which of them corresponds to your sample MobileNet?

Thanks.

**Comment by dsmilkov** [comment]
cc @experiencor since we contributed mobilenet. Would be great to update the mobilenet/README.md with this info.

**Comment by nsthorat** [comment]
The version @experiencor submitted is mobilenet_v1_1.0_224.
