### ISSUE TITLE
MobileNet/YOLO MobileNet not available on npm/unpkg

### ISSUE THREAD

**Issue by Utopiah** [tensorflow/tfjs-core#553]
Both https://github.com/PAIR-code/deeplearnjs/tree/master/models/yolo_mobilenet and https://github.com/PAIR-code/deeplearnjs/tree/master/models/mobilenet point to unpkg link but neither are available via npm.

**Comment by dsmilkov** [comment]
We postponed publishing since we wanted to figure out the scoped npm package solution and unit tests before publishing. We expect to get this done within 2-3 weeks. Thanks for filling this to keep track.

In the meantime, feel free to copy the code in those folder to use it in your project.

**Comment by dsmilkov** [comment]
I'll update the README to clarify that they are not published yet
