### ISSUE TITLE
[Violation] 'requestAnimationFrame' handler took 218ms

### ISSUE THREAD

**Issue by nadendlaprasad** [tensorflow/tfjs-core#556]
When i'm running the model, program is throwing these warning **[Violation] 'requestAnimationFrame' handler took 218ms** messages. This is happening even when i run the model on GPU  machine. Any idea how to improve the performance or what's causing the model to run slowly ? I can observe too much delay sometimes. I am thinking this warning message may be causing the model to run slowly. am i right ?

**Comment by nkreeger** [comment]
Generally, `requestAnimationFrame` is an API that exists for performing animations in a browser. It is designed for the method to run as quickly as possible (https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).

Do you have a link to some code? That might help for tips. Generally, it's best to avoid blocking calls (i.e. NDArray.dataSync()) through this method as much as possible.

**Comment by nadendlaprasad** [comment]
This is happening when i am running teachable machine demo

**Comment by dsmilkov** [comment]
Can you share a bit more info about your setup:
- OS
- Browser
- What machine (e.g. macbook, desktop?) and how old

Thanks

**Comment by nadendlaprasad** [comment]
Laptop Windows 10, chrome browser. It's 5 years old laptop

**Comment by nsthorat** [comment]
Closing this out, feel free to reopen it at https://github.com/tensorflow/tfjs if you are still having issues.
