### ISSUE TITLE
batch eval API

### ISSUE THREAD

**Issue by shady7shen** [tensorflow/tfjs-core#574]
I'm trying to rewrite convnetjs image regression (http://cs.stanford.edu/~karpathy/convnetjs/demo/image_regression.html) using deepLearnjs, but find it hard to match its performance. 
One reason is that I need to eval a large number of (x,y) coordinates to get their corresponding rgb value and it seems that there is no api to do such inference with a batch of inputs.
If it is to be done pixel by pixel, I'm forced to do a dataSync to get each result which is of couse slow.

Could there be a batch inference api ? or is there any alternative way to retrieve a batch of inference result with one dataSync operation?

Thanks and Best Regards
Shady

**Comment by nsthorat** [comment]
We do support batch inference (in our new eager mode, which we don't have documentation for yet and is technically unreleased, but you can start using). Some more details on eager: https://github.com/PAIR-code/deeplearnjs/issues/561

What you can do is set up the input as a [b, d] where b = batchSize (resolution) and d = 2 (x & y), and then train the model using `optimizer.minimize()`. `math.matMul` takes two `Array2D`s (weights, batch of inputs). And of course, in general, you should avoid `dataSync`.

Hope this helps. If you want to send the code you have here, that may be useful as well.

**Comment by shady7shen** [comment]
Thanks, the eager mode seems a lot more straight-forward :) And batch inference in eager mode is quite handy. Hope there will be more optimizers implemented so as to make eager mode productive.

**Comment by nsthorat** [comment]
Yeah, we just need to migrate the optimizers over, but that shouldn't be too far out!

**Comment by nsthorat** [comment]
Filed https://github.com/PAIR-code/deeplearnjs/issues/592

**Comment by nsthorat** [comment]
Eager is launched!
