### ISSUE TITLE
Add generic dot product as a method on NDArray.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs-core#610]
Right now we only have "matMul" which forces you to have 2 Array2Ds, so a vector * matrix becomes:

`v.as2D(-1, m.shape[0]).matMul(m)`

We should simply have to do `v.dot(m)`.

**Comment by nsthorat** [comment]
We also currently have a "dotProduct" method, which we should consolidate under tensordot with the fix for this issue.

**Comment by tafsiri** [comment]
@dsmilkov can this be closed since it is a dup of #664 which is closed?

**Comment by dsmilkov** [comment]
we already marked #664 as dup of this one, so let's keep this open

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#112
