### ISSUE TITLE
Yolo_mobilenet adapt retrain's weight_profile?

### ISSUE THREAD

**Issue by lcycoding** [tensorflow/tfjs-core#620]
Dear Authors,
After trying for few days, I'm almost giving up running Object Detection on web-browser... :(

I was wondering if there's any pre-built packages that consist in the yolo_mobilenet demo.
Since I've trained my yolo_mobilenet model from scratch, but the weight did not fit into the checkpointLoader function. (Note: I've modified the output filter, box_num, num_of_classes.

Is there anything I could be working on rather than just recognizing raccoon on web-browser?

Thanks in advance for your kindly help. 👍

**Comment by nsthorat** [comment]
Now that we have automatic model porting tools with https://js.tensorflow.org/ this might be a little easier. Let us know if you run into any issues there.
