### ISSUE TITLE
how to load gray scale from image to tag

### ISSUE THREAD

**Issue by akshay951228** [tensorflow/tfjs-core#623]
this function 
pixel = dl.Array2D.fromPixels(image);
returns 
Array3D {isDisposed: false, math: NDArrayMath, size: 12288, shape: Array(3), dtype: "int32", …}
but what I want out as Array2d how I can do that?

**Comment by nsthorat** [comment]
This will be fixed in the next release!

**Comment by akshay951228** [comment]
waiting for the release

**Comment by nsthorat** [comment]
fromPixels takes numChannels now: https://js.tensorflow.org/api/0.6.1/#fromPixels
