### ISSUE TITLE
Automatic TensorFlow to deeplearn.js

### ISSUE THREAD

**Issue by lexfridman** [tensorflow/tfjs-core#637]
Do you have an updated timeline for automatically porting GraphDef models to deeplearning.js as this Roadmap shows: https://deeplearnjs.org/docs/roadmap.html

Can I help?

**Comment by nkreeger** [comment]
We're currently working on the design for this feature. We plan to introduce an automatic converter that will export a frozen or saved model automatically to deeplearn.js. Right now, we are planning on introducing a converter that takes the model and exports the graph and the weights into a format that can be easily introduced. Op matching is clearly a major component and we are working on reporting what Ops are unsupported when model conversion takes place.

We hope to have more details soon - but definitely stay tuned for an official announcement soon.

**Comment by carlthome** [comment]
This sounds absolutely fantastic!

**Comment by erikwilson** [comment]
Thanks for everyone's hard work on the 0.5 release! 

It looks like TensorFlow checkpoint support still needs to be worked on, it would be nice if there is generic support so we can use other formats like protobuf, msgpack, raw objects, etc. If there is anything that can be done to help with that please let me know!

It would also be helpful if Semantic Versioning were used for iterating through versions, it appears that 0.5 changes the Scalar constructor enough that my current Graph serialization library is no longer functional. With the removal of Graph support and addition of TensorFlow import/export I hope that DeepLearn will use version 1.0.

As a side note it would be nice to see this functionality tested with DeepSpeech. :)

**Comment by erikwilson** [comment]
Sorry, I feel silly, TensorFlow already uses protobuf.
I imagine something like https://www.npmjs.com/package/tensorflow-tools helps and with https://www.npmjs.com/package/deeplearn-tensorflow by @MarkusBordihn it looks possible to load values but maybe not a recreate a whole model.

**Comment by nsthorat** [comment]
Oh no, I'm sorry @erikwilson. It's a little confusing why we're staying below version 1.0, but we need to for right now without going into all the details.

What specifically broke about the serializer?

**Comment by erikwilson** [comment]
Thanks @nsthorat! It appears that for 1D variables we can no longer do something like `Scalar.new([1], 'bool')`. Beyond that I was receiving some errors about invalid tensor ids, but I have only spent a little bit of time looking at it. Hopefully I was correctly initializing them in the first place, and my library maybe looked at variables that weren't published in the API. I'm sure it's easier to iterate through 0.x versions faster, so keep up the awesome speed and I'm looking forward to more new features! :)

**Comment by nsthorat** [comment]
Ooh I'm sorry, I think the signature changed ever so slightly (unintended, this was supposed to be backwards compatible). All of the constructors moved to top-level constructors, I think this should be straightforward to migrate:

`Scalar.new` => dl.scalar()
`Tensor1D.new` => dl.tensor1d()

More here: https://deeplearnjs.org/docs/api/#Tensors-Creation

Let me know if you run into any other issues.

**Comment by dsmilkov** [comment]
Hi @erikwilson,

Thanks for reporting this. Small suggestion:
I noticed you used `Scalar.new([1], 'bool')` - this was never valid, try Scalar.new(1, 'bool').

Thanks!

**Comment by erikwilson** [comment]
Thanks for the info @dsmilkov, I figured I was doing something wrong, that seems logical so it is nice that the constructor at least informs you that you have the wrong type now. My main issue seems to be that id numbering may have changed a little bit, not really a big deal as I don't think many people use that library anyways and I am happy to obsolete it for something better.

**Comment by erikwilson** [comment]
After playing with this some more it turns out that I am extracting the values from 0.5 incorrectly.

I have a block of code like this:
```
  const dataToJson = (data) => {
    if (data instanceof Tensor) return {id:(data.id-idOffset)}
    const { shape, dtype } = data
    const values = Array.from(data.getValues())
    return { values, shape, dtype }
  }
```

For constants I try to extract the values, it looks like Array*D.new & Scalar.new return Tensor types now so I end up returning the id without values. There is probably a better to do this, not worried about fixing it at the moment but for the sake of transparency wanted to share my finding.

**Comment by jiangts** [comment]
perhaps a bit of a weird question, but would this make it easy to port from deeplearnjs -> tensorflow?

**Comment by nsthorat** [comment]
Woohoo! We launched something that should help with this.

Checkout https://github.com/tensorflow/tfjs-converter

**Comment by carlthome** [comment]
Very cool!
