### ISSUE TITLE
Porting SSD+MobileNet to deeplearnjs

### ISSUE THREAD

**Issue by nadiia-pyvovar** [tensorflow/tfjs-core#676]
We trained an 
[object detection model](https://github.com/tensorflow/models/tree/master/research/object_detection) and want to port it to run in browser. We tried to convert the graph using the  [mnist example](https://deeplearnjs.org/demos/mnist/mnist.html), but have problems with graph description in MODEL_NAME.ts file. We try to imitate files in models/yolo_mobilenet, but they don't seem to work.
We saw, that there will be an automatic model porter, but how soon is it going to be released?

**Comment by nsthorat** [comment]
@pyu10055 @nkreeger for more information about auto model porting.

**Comment by tafsiri** [comment]
@nadiia-pyvovar just want to update this as we have released some model porting tools (supports TensorFlow SavedModel and Keras models). Some relevant tutorials for this are available here https://js.tensorflow.org/tutorials/

Please give it a try and let us know how it goes!
