### ISSUE TITLE
[Noob] - Train an LSTM Example

### ISSUE THREAD

**Issue by talvasconcelos** [tensorflow/tfjs-core#677]
Guys, i'm a noob at ML, been messing around with Synaptic and Neataptic libraries and have seen some success. I'd like to try deeplearn but it seems too "mathy" to me. 

The reason i used the above libraries are 1) they are in JS and 2) they had already built functions for LSTM, GRU, etc... One can start a training session with declaring the network: LSTM(2, 3, 1)... 2 input nodes, 3 hidden layers and 1 output. The problem is they run on CPU and i have a big chunk of data to train and it takes forever! (i have +/- 50000 data entries)

Is there any simple tutorial where i can start with and learn how i can train an LSTM with deeplearn? I'm failing to understand the NDArray and Tensors etc... I looked in the example folder form deeplearn but failed to understand the creation of the RNN.

I have the data in array already with the format: 
```
[
    {input: [1, 2, 3, ...n], output:[1]},
    {input: [1, 2, 3, ...n], output:[1]},
    ...
]
```
I want an LSTM with 5 inputs and 1 output.
Can someone hepl or point me in the right direction?

**Comment by tafsiri** [comment]
Hi @talvasconcelos, I don't think we are able to train LSTM's at the moment. We are working on some changes that should enable this soon (in the next week or so), but it might be a while before we have higher level apis or tutorials for this. However its helpful to know which tutorials will be helpful for folks as we plan out which ones we do next so thanks for posting!

One thing you might want to keep an eye on is https://itpnyu.github.io/ml5/ its a higher level library that wraps deeplearn.js. I believe they have an example of running inference using an LSTM, (though the training step for that example is in python).

**Comment by kwhitley** [comment]
Hey @talvasconcelos I'm in the same boat as you - and if no one else makes a high level API/wrapper on deeplearn.js, I will... I too think the API to synaptic and neataptic are amazing, but the performance lacks.  Bringing those two worlds together would be a huge leap forward for ML in the browser/Node!

**Comment by talvasconcelos** [comment]
Oh man, if you get it up and running it would be amazing!! I'm trying to train on 50k plus lines of data with 12 inputs and my pc is about to stand up and run out the door!!

**Comment by kwhitley** [comment]
Totally feel the pain... those libs appear to have (for the most part) been beautifully designed, but it's not even using efficient structures for *javascript*, much less compared to vectorized implementations in Python, some JS libs, etc.

I will say, if you're not too concerned with overfit or getting caught in local minimums, the neataptic NEAT implementation is remarkably fast to evolve great fitting agents - although the docs are rather weak.

**Comment by talvasconcelos** [comment]
I'm a ML noob, that's why i stayed away from it, but i'll give it another
look. At the moment im using the evolve from Neataptic that performs ...
well, faster than the training at least!

**Comment by kwhitley** [comment]
It's definitely fun to "grow" agents and watch them get better at whatever task you're trying to fit them on (in my case, they learn day-trading strategies)... but as I mentioned, they can get caught in local minimums.  For example, if they discover one path that nets them a higher score, they charge down that path alone, without exploring all options.  Novelty Search would be a way to explore more of the search area, but Neataptic doesn't implement that, and online docs in general on how to encode that seem sparse at best.

**Comment by talvasconcelos** [comment]
I'm also trying trading analysis... :)
Can we a chat? I'll send you an email..

**Comment by kwhitley** [comment]
Totally @talvasconcelos  - hit me up at krwhitley@gmail.com!  Would definitely help to collab with others on this!

**Comment by kwhitley** [comment]
@tafsiri I definitely second this - and training examples in JS would be marvelous.  If I can even see how it's formed, I can implement a high-level wrapper (if the ML5 guys don't beat me to it)

👍

**Comment by tafsiri** [comment]
Just to update this thread, with the addition of [slice](https://deeplearnjs.org/docs/api/index.html#dl.slice) in 0.5 it should be possible to implement an LSTM in deeplearn.js. You'd need a reference to the architecture you are implementing (and know how to translate it to the lower level ops deeplearn.js provides).

**Comment by nsthorat** [comment]
Check out https://github.com/tensorflow/tfjs-examples/tree/master/addition-rnn for an example of how to train different types of RNN models with TensorFlow.js
