### ISSUE TITLE
ELU Activation api doesn't allow alpha to be set

### ISSUE THREAD

**Issue by ManrajGrover** [tensorflow/tfjs-core#680]
While adding gradients, I noticed [elu](https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/unary_ops.ts#L173), doesn't allow alpha to be set. Strangely, even [tensorflow](https://www.tensorflow.org/api_docs/python/tf/nn/elu) doesn't allow this. Not sure why.

I can take this one up if we decide to include this.

Reference: https://arxiv.org/pdf/1511.07289.pdf

**Comment by nsthorat** [comment]
Let's stay true to TF here and not implement this for us.
