### ISSUE TITLE
Improve mobile web view for documentation

### ISSUE THREAD

**Issue by ManrajGrover** [tensorflow/tfjs-core#742]
Currently, the view on mobile shows all public methods at the top and documentation after that. I feel we can move the methods under hamburger menu to clean up the view.

Also, after clicking an anchor tag to jump to a section, it hides the api method behind the navigation bar.

I can take this one up.

<img width="773" alt="screen shot 2018-02-17 at 1 08 41 am" src="https://user-images.githubusercontent.com/5673050/36325890-2e8b0150-137f-11e8-830a-6aaea5b8aba6.png">

**Comment by ManrajGrover** [comment]
@nsthorat Should we also add a hamburger menu for mobile or do we plan to change design in near future?

**Comment by dsmilkov** [comment]
Hi @ManrajGrover there will be a website redesign soon. cc @tafsiri who will be driving that effort.

**Comment by tafsiri** [comment]
@ManrajGrover yep I'd probably hold off on this as the site's going to get redesigned and this will page will probably be rewritten.

**Comment by tafsiri** [comment]
Closing this as we have a new site. We can re-open/make a new issue if needed.
