### ISSUE TITLE
Clarify that ML beginners tutorial is in es6

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs-core#756]
To avoid user confusion (see #754), would be nice to clarify that tutorials (e.g. [ML Beginners](https://deeplearnjs.org/docs/tutorials/ml_beginners.html)) are written in es6, and TypeScript users need to add types. Even better might be, in the tutorial, next to every es6 snippet, to have a link to the equivalent TypeScript snippet (same code).

**Comment by tafsiri** [comment]
kk. I can add a note that the examples are all JavaScript. I'm a bit wary of maintaining two sets of examples for both languages at the moment, though if we were to prioritize it maybe some kind of tabbed interface to choose languages. @dsmilkov Can a user initially fix all type issues with `any` annotations?

**Comment by tafsiri** [comment]
Closing for now as we have completely new tutorials and old ones are deprecated.
