### ISSUE TITLE
[Community Idea]  Kaggle alternative for Deeplearn/JavaScript

### ISSUE THREAD

**Issue by QuantumInformation** [tensorflow/tfjs-core#773]
The python folks are pretty lucky in that they have Kaggle. For example there are cool tutorials like so
https://www.kaggle.com/sohier/how-to-integrate-bigquery-pandas where they query data. 

In that example they query a REST service and perform a whole bunch of cool stuff. It would be awesome if the js community had such a tool.

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#132
