### ISSUE TITLE
consider having variable.dispose dispose the underlying tensor as well

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs-core#783]
Consider `let foo = dl.variable(dl.randomNormal([layerInputSize, layerOutputSize], mean, stdDev)); `

Calling `foo.dispose()` and having it dispose the random normal tensor would be very convenient, and possibly reduce a common case of memory leak.

**Comment by tafsiri** [comment]
ping @nsthorat @dsmilkov

**Comment by dsmilkov** [comment]
So we had it like that, but this caused problems and we decided that's very aggressive. We are fine with a single memory leak.

```js
let foo = dl.randomNormal();
let bar = dl.variable(foo);
bar.dispose();
console.log(foo); // foo should be untouched.
```

**Comment by tafsiri** [comment]
So if we stay with current functionality should we change our examples to use that style? Our current examples tend to leak a tensor per variable per model initialization (which can happen multiple times in a session). We can also change the code snippet in our docs.

**Comment by dsmilkov** [comment]
That's a good idea. A bit of good news is that higher-level APIs will hide this detail

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#133
