### ISSUE TITLE
Community Site suggestion.

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tfjs-core#797]
As Deeplearnjs moves towards version 1.0 is there a plan for a Community Page or Google Group to support the hundreds of users with varying levels of Javascript ability as they descend on this Github Site? 

A well setup Community Site can shelter the Deeplearnjs team members from the FAQ questions of Noobs, or programming issues that are not the fault of Deeplearnjs. 

When developing my [Robotics Curriculum](https://www.youtube.com/playlist?list=PL57Dnr1H_egsL0r4RXPA4PY2yZhOJk5Nr) most of my [49 questions](https://community.particle.io/u/rocksetta/summary) were answered by community members not on payroll with https://www.particle.io/

Beginners are also much more likely to ask a question on a [Community Site](https://community.particle.io/) than post an issue to Github.

**Comment by nsthorat** [comment]
This is a phenomenal idea. If I have a question about "how do I do xyz in keras" I probably wouldn't file an issue there.

@tafsiri curious what your thoughts are on this :)

**Comment by tafsiri** [comment]
@hpssjellis @nsthorat this is definitely something we are thinking about. No firm plans yet, but I imagine a possible first step for us might be to direct people to StackOverflow and keep track of that a bit better. And possibly start a mailing list/google group. Its definitely on our radar as the library matures and becomes more accessible.

**Comment by hpssjellis** [comment]
@nsthorate @tafsiri.  Already a small bit of Deeplearnjs action on Stackoverflow at [https://stackoverflow.com/search?q=deeplearnjs](https://stackoverflow.com/search?q=deeplearnjs) . That works for the programming issues, not the best for "how do I do xyz in keras", perhaps a Google Group would be best for theoretical discussions. Not sure how you would direct people to those platforms.

**Comment by QuantumInformation** [comment]
Yup theres a discord channel and a London meetup

https://www.meetup.com/London-DeepLearn-js-Meetup/
https://discord.gg/64MVzQX

**Comment by nsthorat** [comment]
We decided against an official site, however we have the mailing list: groups.google.com/a/tensorflow.org/forum/#!forum/tfjs
