### ISSUE TITLE
Add dl.randomShuffle.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs-core#801]
This would mirror:
https://www.tensorflow.org/api_docs/python/tf/random_shuffle

**Comment by jgartman** [comment]
Looks like Tensorflow only has a CPU version of random_shuffle.  Is it safe to assume we'd want both a CPU and WebGL implementation here?

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#134
