### ISSUE TITLE
Dynamic module imports of deeplearnjs

### ISSUE THREAD

**Issue by QuantumInformation** [tensorflow/tfjs-core#808]
Tsc allows dynamic imports https://blog.mariusschulz.com/2018/01/14/typescript-2-4-dynamic-import-expressions

I'd like to be able to run some code without compiling deeplearnjs into my builds, is there any way we could do something like this?

tensors.ts
```ts
async function importDeeplearnAndRun () {
  const dl = await import("../node_modules/deeplearn/dist")
  dl.tensor([1, 2, 3, 4]).print()
}

importDeeplearnAndRun()
```
```html
  <script type="module" src="tensors.js"></script>
```
So with a minimal tsc run on the ts file about we could run examples in the browser just importing the deeplearn that they need? Otherwise I think webpack is the way to go to reduce file size.

**Comment by tafsiri** [comment]
Hi @QuantumInformation, we haven't built any projects with dynamic import so i can't comment on this directly. But I'd say it really depends on how you bundle/serve the project you are working on. If you are targetting a browser that supports dynamic import then tsc transpilation might be enough. Else you'd have to use some kind of bundler to turn that import into something the browser can run. 

Webpack or browserify are great candidates for that. You should be able to exclude dependencies like deeplearn.js from your project bundle using [webpack vendoring](https://webpack.js.org/concepts/entry-points/#separate-app-and-vendor-entries) or [browserify shim](https://github.com/thlorenz/browserify-shim)

**Comment by QuantumInformation** [comment]
ATM I'm just using webpack. I think internally it does tree shaking.

**Comment by tafsiri** [comment]
Is your goal to produce a bundle where deeplearn.js is not included?
