### ISSUE TITLE
Формат файлов checkpoint

### ISSUE THREAD

**Issue by PABCSoft** [tensorflow/tfjs-core#834]
В каком формате хранятся файлы обученной сети? Как можно загрузить веса из файлов checkpoint в программе на C/C++/C#?

**Comment by hpssjellis** [comment]
Gotta love [Google Translate](https://translate.google.ca/): 

Here is @PABCSoft question translated

> В каком формате хранятся файлы обученной сети? Как можно загрузить веса из файлов checkpoint в программе на C/C++/C#?



In what format are the files of the trained network stored? How can I load weights from checkpoint files in a program in C / C ++ / C #?

Not sure if you want the reply in Russian.

Не уверен, хотите ли вы ответ на русском языке

**Comment by PABCSoft** [comment]
Write in the language in which you will be comfortable. If only it was detailed and clear. I am interested to know about the file structure itself. I understood only that the data is stored in the Single type(Float32). How to read byte-by-byte file I do not understand. Particularly interested in Your example of Fast Neural Style Transfer. Unfortunately, I don't know Java, but I really want to implement styling in C# .NET. I'd appreciate your help. :smile:

**Comment by hpssjellis** [comment]
@PABCSoft 

The Deeplearnjs guys may have a better answer, but Tensorflow Neural Style Transfer may be closer to C# .net than javascript.  Tensorflow can be written in C and may have more information about the file saving structure.

Lots of examples at:

https://github.com/titu1994/Neural-Style-Transfer

https://www.youtube.com/watch?v=LoePx3QC5Js

https://github.com/cysmith/neural-style-tf

**Comment by PABCSoft** [comment]
Yes, but all examples use a network of 16 VGG and iterative method. And Your example on DeepLearnJS for very fast generation. He's using a network transformer. Apparently, You have not quite understood correctly, I'm trying to write a network ENTIRELY in C#. That is, convolutions, ReLU, all write from scratch on C#. Therefore, you must understand the structure in which the predefined styles are stored.

**Comment by PABCSoft** [comment]
You don't seem to know how this works.
