### ISSUE TITLE
GWT support

### ISSUE THREAD

**Issue by Kjos** [tensorflow/tfjs-core#837]
I've just discovered this framework, and think it's an awesome endeavor :)
To get to the point, I like to do large Javascript projects with GWT and find it's an enormous timesaver and allows me to keep my code clean.
So I've started writing a GWT wrapper for deeplearnjs - haven't come that far yet, but it's a start.
_Any pointers that would make the work easier/better would be appreciated._
I'm thinking to keep structure of the classes mostly the same so the original reference guide can be used.
I take it performance should remain pretty much the same.
One thing I'm wondering is if there are any big changes planned. Would be a shame if I spend time writing a wrapper if there's going to be a big overhaul soon.

Bit offtopic:
How does deeplearnjs compare to tensorflow or others? What is the performance impact when using glsl instead of true gpgpu functionality?

Also a note: the webcam imagenet demo is partly broken. When selecting beer bottle or saxophone, it crashes (Chrome, gpu).

Best of luck,
Kajos

**Comment by QuantumInformation** [comment]
AFAIK deeplearnjs is standalone, but the API is soon to be quite like tensorflow in v 1.

**Comment by nsthorat** [comment]
Obviously we just released the big overhaul. The API will be relatively stable, with us adding support for more ops / layers / serialization stories. Most likely the skeleton wont change.

Hope this helps (closing this issue since we're trying to move all issues to tensorflow/tfjs - feel free to reopen over there).
