### ISSUE TITLE
Unable to run  KNN-image-classifier without an Internet connection

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs-core#841]
While I can cache locally deeplearn.js and deeplearn-knn-image-classifier.js

I see the following in the console when running without an Internet connection. Is there a workaround?

deeplearn.js:3074 GET https://storage.googleapis.com/learnjs-data/checkpoint_zoo/squeezenet1_1/manifest.json net::ERR_INTERNET_DISCONNECTED
(anonymous) @ deeplearn.js:3074
CheckpointLoader.loadManifest @ deeplearn.js:3064
(anonymous) @ deeplearn.js:3081
CheckpointLoader.getCheckpointManifest @ deeplearn.js:3080
(anonymous) @ deeplearn.js:3098
CheckpointLoader.getAllVariables @ deeplearn.js:3097
(anonymous) @ deeplearn-knn-image-classifier.js:1335
step @ deeplearn-knn-image-classifier.js:1313
(anonymous) @ deeplearn-knn-image-classifier.js:1294
(anonymous) @ deeplearn-knn-image-classifier.js:1288
__awaiter @ deeplearn-knn-image-classifier.js:1284
SqueezeNet.load @ deeplearn-knn-image-classifier.js:1328
(anonymous) @ deeplearn-knn-image-classifier.js:67
step @ deeplearn-knn-image-classifier.js:40
(anonymous) @ deeplearn-knn-image-classifier.js:21
(anonymous) @ deeplearn-knn-image-classifier.js:15
__awaiter @ deeplearn-knn-image-classifier.js:11
KNNImageClassifier.load @ deeplearn-knn-image-classifier.js:64
Main @ train.js:124
(anonymous) @ train.js:232
deeplearn.js:3072 Uncaught Error: manifest.json not found at https://storage.googleapis.com/learnjs-data/checkpoint_zoo/squeezenet1_1/. [object ProgressEvent]
    at XMLHttpRequest.xhr.onerror (deeplearn.js:3072)

**Comment by nsthorat** [comment]
Hi @ToonTalk,

What you could do is download the weights of squeezenet1_1 to your local machine. When you have a network connection, download the files that get requested under squeezenet1_1 and the manifest.json to your local machine. 

Unfortunately you'll have to do a little digging to modify the underlying SqueezeNet class that KNNImageClassifier uses and points to the bucket:
https://github.com/PAIR-code/deeplearnjs/blob/master/models/squeezenet/squeezenet.ts#L23

This means you'll need to build a custom SqueezeNet, and a custom KNNImageClassifier which points to the custom SqueezeNet.

**Comment by ToonTalk** [comment]
Thanks. Working now.

If anyone else tries this I found that using Chrome Dev Tools to save all as curl commands and then edit appropriately made creating all the local files pretty painless.

**Comment by hpssjellis** [comment]
My issue is different from @ToonTalk .  My version is ES6 (ish) and is online, it loads the SqueezeNet but does not seem to use the SqueezeNet information. It just compares (correctly) the unknown to the 2 webpage images. Is that what it is supposed to do? If so why load SqueezeNet?

[Github site with demo at](https://github.com/hpssjellis/deeplearnjs-javascript-examples/tree/master/Unordered-javascript-examples/deeplearnjs-examples/knn-image-classifier) 

![knn-classify](https://user-images.githubusercontent.com/5605614/37421349-4f7968ce-2776-11e8-8a2c-76af02d33d47.png)

**Comment by nsthorat** [comment]
KNN Image classifier needs squeezenet to compute an activation :) Closing this out.
