### ISSUE TITLE
when doing division with int32 tensors, a float tensor is returned.

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs-core#847]
Here is a test that demonstrates the issue:   

```javascript
const a = dl.scalar(3).toInt();
const b = dl.scalar(3).toInt();

const result = a.div(b);

expect(result.buffer().values[0]).toBe(1)
```

the test fails with:

> Error: Arrays differ: actual[1] = 3, expected[1] = 0.
> 	Actual:   0.9999999403953552,3.
> 	Expected: 1,0.

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#136
