### ISSUE TITLE
Convert keras models to deeplearnjs

### ISSUE THREAD

**Issue by physicsrob** [tensorflow/tfjs-core#855]
My apologies if this is not the most ideal means of communicating, but I wanted to let the deeplearnjs community know about a project I've started.  I'm interested in potentially deploying models developed and trained in keras to deeplearn.js (as well as other platforms), so I've written a conversion tool: https://github.com/gradecam/keras_to_deeplearnjs. This is hot off the presses so still very much alpha.

A few minor things to highlight:
- The converter takes keras h5 files and converts it to a commonjs module plus a single weight file with all the weights.  The commonjs module loads the weights file and exports an infer function that runs the model.
- I've included an mnist example that uses the deeplearnjs mnist example modified to run based on a model trained using keras's mnist_cnn.py example.
- Without using this tool it's of course already possible to convert a keras model to tensorflow, and then convert tensorflow to deeplearn.js, but I'm not convinced doing so is ideal (especially considering the tooling only supports converting the weights from tensorflow at this point). 
- I plan on adding many more layer types in the coming week.

I'd be happy to put this into a PR targeting deeplearnjs, but considering it depends on the keras API it seems more appropriate to keep it separate.

Cheers!  (and great work -- I'm impressed with deeplearn.js and hope to make some contributions)

**Comment by kimamula** [comment]
I have a similar requirement though importing only weights is OK in my current project.

Therefore I have implemented `KerasModelDumper` which extends `CheckpointDumper`.

https://github.com/kimamula/deeplearnjs/commit/5d1eea652833a63f027400cf9c3c40a2079caabd

I would like a feature like at least either of @physicsrob's tool or my `KerasModelDumper` to be officially provided by deeplearn.js.

**Comment by nsthorat** [comment]
Thanks for all the hard work everyone, this is really fantastic.

We're working on some model porting scripts ourselves, maybe once we release them in a few weeks we can see where there they are similar and dissimilar and try to merge efforts?

We checked in the first part of it which shards weights files so they get cached in the browser as part 1. You can find that python [here](https://github.com/PAIR-code/deeplearnjs/blob/master/scripts/write_weights.py)

**Comment by physicsrob** [comment]
Thanks for pointing towards write_weights.  I think I'm going to refactor my project to use that for saving weights.  In addition now that I've written it once I think I have some ideas to refactor it to be more reusable hopefully outside the context of keras.

I'm excited to see the official tensorflow conversion script.  It's entirely possible it'll solve my use case entirely.  We'll see. :)

**Comment by physicsrob** [comment]
One thought:  If deeplearnjs had a mechanism for building a model from a JSON model description then any model converter (or builder) could just target that JSON model description format.  That seems like something that might be very worthwhile to include.  If the tensorflow converter targeted that JSON format it would have a nice side effect of producing a good separation of concerns.  If it still made sense to have a keras->deeplearnjs converter (as a separate project) that project would target the intermediate JSON format.  If any other frameworks were being used for creating models it would be relatively easy to build converters to that intermediate format...  Just a thought.

**Comment by reiinakano** [comment]
@physicsrob That sounds like https://github.com/onnx/onnx :)

**Comment by tafsiri** [comment]
Hi @physicsrob, I also want to point you to the newly released Keras model importer/converter. Here is a tutorial we wrote up with the new API https://js.tensorflow.org/tutorials/import-keras.html, not sure how this impacts plans for your tool, but you can take a look and see what you think.

**Comment by physicsrob** [comment]
I saw that this morning.  Fantastic -- I'm thrilled that converting keras models is a first class citizen!  I plan on killing my tool.  No need to maintain something separate as far as I can see.  I'd rather contribute to the official repo if there's anything inadequate in the official tool (which seems unlikely).

**Comment by dsmilkov** [comment]
We would love your contributions, Rob!
