### ISSUE TITLE
Why chrome's console  reports an error "Uncaught TypeError: dl.tensor1d is not a function"?

### ISSUE THREAD

**Issue by cyilu** [tensorflow/tfjs-core#869]
I am trying the basic code:
`
import * as dl from 'deeplearn'; // If not loading the script as a global

const a = dl.tensor1d([1, 2, 3]);
const b = dl.scalar(2);

const result = a.add(b); // a is not modified, result is a new tensor
result.data().then(data => console.log(data)); // Float32Array([3, 4, 5]

// Alternatively you can use a blocking call to get the data.
// However this might slow your program down if called repeatedly.
console.log(result.dataSync()); // Float32Array([3, 4, 5] `

But there report an error "Uncaught TypeError: dl.tensor1d is not a function", when I open the index.html.

**Comment by ManrajGrover** [comment]
Hi @cyilu,

Please check if you've added the script tag for loading deeplearnjs. Please see https://github.com/PAIR-code/deeplearnjs#usage for the same.

**Comment by cyilu** [comment]
Yes I have had. If the code change to the starter code.
`import 'babel-polyfill';
import {Array1D, ENV, Scalar} from 'deeplearn';

/** Runs the example. */
async function runExample() {
  const math = ENV.math;
  const a = Array1D.new([1, 2, 3]);
  const b = Scalar.new(2);

  const result = math.add(a, b);


  // Option 1: With async/await.
  // Caveat: in non-Chrome browsers you need to put this in an async function.
  console.log(await result.data()); // Float32Array([3, 4, 5])

  // Option 2: With a Promise.
  result.data().then((data) => console.log(data));

  // Option 3: Synchronous download of data.
  // This is simpler, but blocks the UI until the GPU is done.
  console.log(result.dataSync());
  console.log("hahaha");
}

runExample();`


It's OK.

**Comment by ManrajGrover** [comment]
I would need more information here. Did you transpile the code to ES5 before running it in the browser or are you directly running the example shared

 If you're running it directly with script tag, you don't need to import the library ie. remove `import * as dl from 'deeplearn';`. 

 If you're running it after transpiling the code, it will work as expected like in your second example.

Could you please create a gist for the same if problem persists? It will help make debugging easier. https://gist.github.com
