### ISSUE TITLE
Why dl.equal return [9,9,9,...,9,9,9,9]?   

### ISSUE THREAD

**Issue by cyilu** [tensorflow/tfjs-core#878]
The  tensor a is:
    [5, 1, 8, ..., 1, 1, 4]
The tensor b is:
    [0, 0, 0, ..., 0, 0, 0]
The dl.equal(a, b) return:
    [9, 9, 9, ..., 9, 9, 9]
I think what it should be is true of flase?

**Comment by tafsiri** [comment]
Hi @cyilu Would you be able to post a code snippet? I tried the following 

```js
var a = dl.tensor([5, 1, 8, 1, 1, 4]);
var b = dl.tensor([0, 0, 0, 0, 0, 0]);

console.log(dl.equal(a,b).dataSync())
```

and i get `Uint8Array(6) [0, 0, 0, 0, 0, 0]` as output.

If I change the last value in tensor b to a `4` then I get `Uint8Array(6) [0, 0, 0, 0, 0, 1]`. 0 represents false while 1 represents true. 

Is it possible that your two tensors are not the same size? You could also try `dl.equalStrict` to make sure that they are the same shape.
