### ISSUE TITLE
add mod op?

### ISSUE THREAD

**Issue by riatzukiza** [tensorflow/tfjs-core#884]
```js
dl.tensor1d([11,22,33,44,55,66,77,88,99]).mod(10);
// [1,2,3,4,5,6,7,8,9]
```

**Comment by ManrajGrover** [comment]
Hi @riatzukiza,

Thanks for creating an issue for this. I've raised a PR (#887). You can follow the progress there.

**Comment by nsthorat** [comment]
Thanks everyone. We'll get to these soon, I promise :)
