### ISSUE TITLE
Not exported functions on index

### ISSUE THREAD

**Issue by Fdom92** [tensorflow/tfjs-core#886]
Hi, i was trying to use the cpnn art example to start using deeplearn but i'm getting some errors:

```
[ WARN  ]  'ones' is not exported by 'node_modules/deeplearn/dist/index.js'
[ WARN  ]  'truncatedNormal' is not exported by 'node_modules/deeplearn/dist/index.js'
[ WARN  ]  'tidy' is not exported by 'node_modules/deeplearn/dist/index.js'
[ WARN  ]  'scalar' is not exported by 'node_modules/deeplearn/dist/index.js'
[ WARN  ]  'tensor2d' is not exported by 'node_modules/deeplearn/dist/index.js'
```

I'm using node v 6.11.0 and v 8.3.0 with same results
I'm using this starter [https://github.com/ionic-team/stencil-app-starter](https://github.com/ionic-team/stencil-app-starter)
And i'm using the latest version of the deeplearn npm package (0.5.1)

Thanks for this cool tool 👍

**Comment by tafsiri** [comment]
Hi @Fdom92 do you have a repository on GitHub i could take a look at? I don't know enough about that starter's build system to comment much further on what may be going on.

**Comment by Fdom92** [comment]
Sure @tafsiri, this is the link https://github.com/Fdom92/stencil-cnnp

Hope this can be helpful.

**Comment by tafsiri** [comment]
Thanks @Fdom92, we suspect that the issue _may be_ that your build system (it looks like rollup is being used under the hood) may expect es6 style exports, however our deeplearn distribution is already transpiled down to es5. 

Does that sound like it might be the issue? Have you used other projects via node_modules with stencil starter project?

**Comment by Fdom92** [comment]
Yes, it seems to be the issue cause for example:

const a = dl.tensor1d([1, 2, 3]); -> const a = dl.Tensor1D.new([1, 2, 3]);

This change is needed in order to get this working, so maybe the stencil build process

**Comment by Fdom92** [comment]
Hi @tafsiri got it working, not the best way but works, i updated the repo if you want to check out how.

Thanks for the help and good tool :)

**Comment by tafsiri** [comment]
Sweet! Glad to see you got it working!
