### ISSUE TITLE
How to export model

### ISSUE THREAD

**Issue by hbtech-ai** [tensorflow/tfjs-core#89]
my own dataset is training ok,but i can not find some method export trained model @nsthorat

**Comment by hbtech-ai** [comment]
I will export ckpt

**Comment by kaihuchen** [comment]
@hbtech-ai  I believe that this is a feature that the team is still working on. There are some relevant discussions [here](https://github.com/PAIR-code/deeplearnjs/issues/33)

**Comment by nsthorat** [comment]
Yeah, we're not actively working on this right now, but will get to it at some point in the future. Check out @kaihuchen's comment about other discussions. If you want to send us a PR that lets you save weights we will merge it!

**Comment by jafaircl** [comment]
Any update on this with the new API? It'd be great to be able to train and save a model to pull in later for inferences or more training.

**Comment by nsthorat** [comment]
Here is the issue that will be tracking it. The team is taking a break for a day or two given our mad rush to the launch, but we'll be looking at this really soon!

https://github.com/tensorflow/tfjs/issues/13

**Comment by dsmilkov** [comment]
Closing per previous comment that this will be tracked as tensorflow/tfjs#13.
