### ISSUE TITLE
Complementary Colors tutorial is confusing without the source code for reference

### ISSUE THREAD

**Issue by EFHIII** [tensorflow/tfjs-core#901]
With the Complementary Colors demo deleted, it's very confusing for someone unfamiliar with DL to figure out how everything works, and where to find an implemented example of the Complementary Colors tutorial.

**Comment by QuantumInformation** [comment]
You should be able to port it by using tf instead of dl.

**Comment by nsthorat** [comment]
It would be cool if somebody would port this demo to an Observable notebook using the layers API!

**Comment by dsmilkov** [comment]
Also checkout our new examples in [tensorflow/tfjs-examples](https://github.com/tensorflow/tfjs-examples). We don't have the complementary color prediction but we believe the examples we have cover a wide variety and show the possibilities of the library.
