### ISSUE TITLE
Why parseGrayscaleImageData  and parseRGBImageData of xhrdataset have the same function?

### ISSUE THREAD

**Issue by cyilu** [tensorflow/tfjs-core#902]
I think these two function are alike:
`
  function parseGrayscaleImageData(
    data: Uint8Array|Uint8ClampedArray, result: Uint8Array,
    resultOffset: number): void {
  let idx = resultOffset;
  for (let i = 0; i < data.length; i += 4) {
    result[idx++] = data[i];
  }
}

function parseRGBImageData(
    data: Uint8Array|Uint8ClampedArray, result: Uint8Array,
    resultOffset: number): void {
  let idx = resultOffset;
  for (let i = 0; i < data.length; i += 4) {
    result[idx] = data[i];
    result[idx + 1] = data[i + 1];
    result[idx + 2] = data[i + 2];
    idx += 3;
  }
}`

**Comment by nsthorat** [comment]
The functions are slightly different, one is parsing a grayscale image (just parsing red channel), and the other is parsing the fully packed RGB byte array. Notice the inner for loop is different.

**Comment by cyilu** [comment]
@nsthorat But the "data" is 1d array. Therefore, "data" to "result" is 1d array to 1d array. Isn't it？

**Comment by nsthorat** [comment]
ImageData is always a flat array, you can check out the docs here: https://developer.mozilla.org/en-US/docs/Web/API/ImageData

**Comment by cyilu** [comment]
@nsthorat Yes, ohhh， now I think the size of the "result" is N*(shape[0]*shape[1])， so the size of the "result" is not equal to the “data” .

**Comment by dsmilkov** [comment]
This issue was moved to tensorflow/tfjs#68
