### ISSUE TITLE
Add support for additional random tensors

### ISSUE THREAD

**Issue by jgartman** [tensorflow/tfjs-core#903]
Deeplearn.js currently supports tensors of random samples drawn from normal, truncated normal or uniform distributions and it looks like multinomial sampling is being added back to the api soon.  Tensorflow’s random_ops supports all of these as well as the [poisson](https://www.tensorflow.org/api_docs/python/tf/random_gamma), and [gamma](https://www.tensorflow.org/api_docs/python/tf/random_poisson) distributions.  I was wondering if it would be worthwhile to support these in deeplearn.js as well?

Thanks

**Comment by dsmilkov** [comment]
This issue was moved to tensorflow/tfjs#67
