### ISSUE TITLE
Starter Project links broken

### ISSUE THREAD

**Issue by kriptontr** [tensorflow/tfjs-core#906]
Starter project links at homepage   are broken  
https://deeplearnjs.org/index.html#demos
https://github.com/PAIR-code/deeplearnjs/tree/master/starter/es6/
https://github.com/PAIR-code/deeplearnjs/tree/master/starter/typescript/

**Comment by nsthorat** [comment]
Apologies, we're in the middle of moving some code to other repositories. We'll send an update on Friday with where all the code now lives!

**Comment by tafsiri** [comment]
Hi @kriptontr We are moving demos/starter projects to a new repo with the launch of https://js.tensorflow.org/ See https://github.com/tensorflow/tfjs-examples for the things start off from. With this we are removing starter projects from the main repository.

We are keeping up the old site for a while to make the transition easier but it is essentially deprecated.

**Comment by kriptontr** [comment]
great news. thank you .
