### ISSUE TITLE
demos broken on master

### ISSUE THREAD

**Issue by physicsrob** [tensorflow/tfjs-core#911]
Demos are broken on master after moving some of the files out of the repo.  Also the 'yarn prep' command is gone, which means users need to run yarn from the root directory and the demos directory, which I don't think is particularly obvious.

I'm sure this is part of the big shuffle and will be resolved shortly.

One question:  Is there any sort of slack/irc channel for this project?  It'd be nice to be able to communicate in a less formal manner than creating issues.

**Comment by tafsiri** [comment]
@physicsrob. Yep we are moving demos to a new repo with the launch of https://js.tensorflow.org/  See https://github.com/tensorflow/tfjs-examples for the demos we plan on maintaining. We will be removing a fair amount of the older demos.

We also started a community mailing list for discussion. https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs

**Comment by physicsrob** [comment]
So is the plan then to remove the existing demos in this repo?  If so, I want to strongly encourage that the benchmark tool isn't removed (or is migrated to the other repo).  It's a very effective way of learning the performance characteristics of tfjs, which I consider to be a highly useful step for anyone who plans on using tfjs in a production environment.

**Comment by tafsiri** [comment]
Yes we will generally be removing demos from this repo, possibly porting some to @tensoflow/tfjs-examples (we want to centralize demos/examples there as much as we can). Some of the demos use now deprecated APIs so they might come back in future, but we'll look at this case by case.

Definitely hear you on the benchmarks keeping benchmarks available. We also have another benchmark here https://github.com/tensorflow/tfjs-layers/blob/master/integration_tests/benchmarks/index.html for the new higher level api (which depends on tfjs-core).

**Comment by QuantumInformation** [comment]
@tafsiri We also have a discord server where people can get real-time info and interaction on tfjs.

https://discord.gg/64MVzQX

**Comment by dsmilkov** [comment]
This issue was moved to tensorflow/tfjs#62
