### ISSUE TITLE
Why mobileNet.predict() hit a performance cliff after certain amount of runs?

### ISSUE THREAD

**Issue by samwyi** [tensorflow/tfjs-core#925]
#### Describe the problem or feature request
mobileNet.predict() hit a performance cliff after certain amount of runs.
On my MacBook Pro, the average of 100 runs is ~11ms, while the average of 200 runs drops to ~46ms. Similar issue happened on my Android device. I wonder what caused the performance drop? Anyway to avoid it? Thanks.

#### Code to reproduce the bug / link to feature request:
Change tfjs-converter/demo/index.js cat.onload() code to call mobileNet.predict() multiple times in a loop:

  console.time('Subsequent predictions');
  for (let i = 0; i < 200; i++) {
      result = mobileNet.predict(pixels);
  }
  console.timeEnd('Subsequent prediction');

**Comment by nsthorat** [comment]
Try `await tf.nextFrame()` between each tick (you may have to wrap your code in a function marked as async).

```
async function run() {
  console.time('Subsequent predictions');
  for (let i = 0; i < 200; i++) {
    result = mobileNet.predict(pixels);
    await tf.nextFrame();
  }
  console.timeEnd('Subsequent prediction');
}
run();
```

**Comment by nsthorat** [comment]
This issue was moved to tensorflow/tfjs#145
